# Generated by Django 5.2.5 on 2025-10-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='available',
            new_name='is_available',
        ),
    ]
